# Generated by Django 5.2.13 on 2026-05-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_url', models.CharField(max_length=255)),
                ('project_photo', models.ImageField(upload_to='project_imgs')),
                ('project_description', models.CharField(max_length=255)),
            ],
        ),
    ]
