# Generated by Django 5.2.13 on 2026-05-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=128)),
                ('message', models.CharField(max_length=1785)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
