# Generated by Django 5.2.13 on 2026-05-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=64)),
                ('repo_url', models.CharField(max_length=255)),
                ('commit_url', models.CharField(max_length=255)),
                ('commit_id', models.CharField(max_length=16, unique=True)),
                ('message', models.CharField(max_length=255)),
                ('project_url', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('video_id', models.CharField(max_length=32, unique=True)),
                ('thumbnail_url', models.CharField(max_length=128)),
                ('uploaded_at', models.DateTimeField()),
            ],
        ),
    ]
