# Generated by Django 5.2.13 on 2026-05-02 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_githubhistory_youtubehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubhistory',
            name='project_url',
        ),
    ]
