# Generated by Django 5.2.13 on 2026-05-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_remove_githubhistory_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.CharField(max_length=178),
        ),
    ]
