"""
Django settings for ingo project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from environs import env
from pathlib import Path
from django_components import ComponentsSettings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str(
    "SECRET_KEY",
    default="django-insecure-4zv!2bn@d4cjl^mb@4fqb!d+4r&^^g4)*&$zo32z@02net!ei7",
)

DISCORD_WEBHOOK = env.str(
	"DISCORD_WEBHOOK",
	default=""
)

GIT_SECRET = env.str(
	"GIT_SECRET",
	default=""
)

YOUTUBE_SECRET = env.str(
	"YOUTUBE_SECRET",
	default=""
)

YOUTUBE_CHANNEL = env.str(
	"YOUTUBE_CHANNEL",
	default=""
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", default=False)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[''])

CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.messages",
    "django.contrib.sessions",
    "django.contrib.sites",
    "django.contrib.staticfiles",
    "landing",
]

# Third-party apps

INSTALLED_APPS += [
    "django_browser_reload",
    "django_prodserver",
    "django_q",
    "django_tailwind_cli",
    "django_components",
    "health_check",
    "hcaptcha_field",
]

# Our apps

INSTALLED_APPS += []

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_browser_reload.middleware.BrowserReloadMiddleware",
]

ROOT_URLCONF = "config.urls"

HCAPTCHA_SITEKEY = env.str(
    "HCAPTCHA_SITEKEY",
	default=""
)
HCAPTCHA_SECRET = env.str(
    "HCAPTCHA_SECRET",
	default=""
)

HCAPTCHA_TIMEOUT = 5

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            str(BASE_DIR.joinpath("templates")),
            str(BASE_DIR.joinpath("components")),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "landing.context_processors.admin_media",
            ],
            "debug": DEBUG,
            "builtins": [
                "django_components.templatetags.component_tags",
            ],
        },
        
    },
]

ASGI_APPLICATION = "config.asgi.application"

COMPONENTS = ComponentsSettings(
    #    autodiscover=True,
    dirs=[BASE_DIR / "components"],
    app_dirs=["components", "landing"],
    #    libraries=[],
    #    context_behavior="isolated",  # "django" | "isolated"
)

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": env.dj_db_url("DATABASE_URL", default="postgres:///ingo"),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_ROOT = str(BASE_DIR.joinpath("static"))
STATIC_URL = "/static/"
STATICFILES_DIRS = (str(BASE_DIR.joinpath("frontend")),)
# STORAGES = {
#    "staticfiles": {
#         "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"
#     }
# }

MEDIA_URL = "/media/"
MEDIA_ROOT = str(BASE_DIR.joinpath("media"))

if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    email = env.dj_email_url("EMAIL_URL", default="smtp://maildev")
    EMAIL_HOST = email["EMAIL_HOST"]
    EMAIL_HOST_PASSWORD = email["EMAIL_HOST_PASSWORD"]
    EMAIL_HOST_USER = email["EMAIL_HOST_USER"]
    EMAIL_PORT = email["EMAIL_PORT"]
    EMAIL_USE_TLS = email["EMAIL_USE_TLS"]

# Parse cache URLS, e.g "redis://localhost:6379/0"
CACHES = {"default": env.dj_cache_url("CACHE_URL", default="locmem://")}

# Our settings

ADMIN_URL = env.str("ADMIN_URL", default="admin/")

SITE_ID = 1

# Tailwind CSS settings

TAILWIND_CLI_AUTOMATIC_DOWNLOAD = env.bool("TAILWIND_CLI_AUTOMATIC_DOWNLOAD", default=True)
TAILWIND_CLI_DIST_CSS = env.str("TAILWIND_CLI_DIST_CSS", default="css/tailwind.css")
TAILWIND_CLI_SRC_CSS = env.str("TAILWIND_CLI_SRC_CSS", default="frontend/index.css")
TAILWIND_CLI_VERSION = env.str("TAILWIND_CLI_VERSION", default="4.2.1")

# Django-Q2 settings

Q_CLUSTER = {
    "bulk": 10,
    "max_attempts": 1,
    "name": "ingo",
    "orm": "default",
    "queue_limit": 50,
    "recycle": 500,
    "retry": 120,
    "timeout": 60,
    "workers": 2,
}

# Django Prodserver settings

PRODUCTION_PROCESSES = {
    "web": {
        "BACKEND": "django_prodserver.backends.gunicorn.GunicornServer",
        "ARGS": {
            "bind": "0.0.0.0:8000", 
            "workers": "2",
            "worker-class": "uvicorn.workers.UvicornWorker",
        },
        "APP": "config.asgi:application",
    },
    "worker": {
        "BACKEND": "django_prodserver.backends.django_q2.DjangoQ2Worker",
        "ARGS": {},
    },
}
